spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candyShop?currentSchema=candyShop
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
security:
  jwt:
    secret: aGVsbG9mcm9tY2F0Y2h0aGVtb21lbnRhcHBsaWNhdGlvbnVzZXRoaXNhcHB3aXRob3V0YW55RGlmZmljdWx0aWVz
    access: 3600000
    refresh: 2592000000
