spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candyShop?currentSchema=candyShop
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
