spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candyShop?currentSchema=candyShop
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false

security:
  jwt:
    secret: bWFybXV6Q2FuZHlTaG9wQXBwbGljYXRpb25Gb3JUYWtlQmlnU3VtT2ZNYW55
    access: 3600000
    refresh: 2592000000
